###
@server = http://localhost:9002

###
@api = {{server}}/v1

### token
@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWYiOiI2NThjNWJjZWNmZWY5MjFkMWIwODg0OTUiLCJyb2xlIjoic3VwcGxpZXIiLCJpYXQiOjE3MDM3NDMyNjksImV4cCI6MTg3NjU0MzI2OSwiYXVkIjoid2ViLXVzZXIiLCJpc3MiOiJzaG9wRXhwbG9yZS1kZXZlbG9wbWVudCJ9.obYNpuiSGx25OI5faHF0vKna5av5NtTg8VNLKeEHZT4

###
GET {{server}}

###
GET {{api}}

### create product
POST {{api}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productName": "Iphone 15",
    "category": "electronics",
    "description": "apple latest product",
    "price": 1200,
    "quantityInStock": 90,
    "lowStockAt": 10
}

### delete product
DELETE {{api}}/products/657a72f5848260ca33053dc5
Authorization: Bearer {{token}}

### edit product
PATCH  {{api}}/products/edit-product
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "productId": "657a72f5848260ca33053dc5",
    "productName": "Iphone 19",
    "category": "electronics",
    "description": "apple latest product",
    "price": 19000,
    "quantityInStock": 800,
    "lowStockAt": 100
}

### search product
GET {{api}}/products/search-product

### add product to cart
### remove from cart
